export const ALL_PRODUCTS_REQUEST_START = 'ALL_PRODUCTS_REQUEST_START';
export const ALL_PRODUCTS_REQUEST_SUCCEEDED = 'ALL_PRODUCTS_REQUEST_SUCCEEDED';
export const ALL_PRODUCTS_REQUEST_FAILED = 'ALL_PRODUCTS_REQUEST_FAILED';
